SET IDENTITY_INSERT NoteFever_EvernoteClone.dbo.Language ON;

INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (213, 'en-US', 'LoginViewLocal', 'Or use it');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (214, 'en-US', 'LoginViewLocalHyperlink', 'Locally');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (211, 'en-US', 'LoginViewLogin', 'Login');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (210, 'en-US', 'LoginViewPassword', 'Password');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (212, 'en-US', 'LoginViewRegister', 'Register');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (209, 'en-US', 'LoginViewUsername', 'Username');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (228, 'en-US', 'NewNoteViewEditDelete', 'Delete');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (222, 'en-US', 'NewNoteViewEdit', 'Edit');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (226, 'en-US', 'NewNoteViewEditCopy', 'Copy');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (225, 'en-US', 'NewNoteViewEditCut', 'Cut');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (230, 'en-US', 'NewNoteViewEditFindAndReplaceAll', 'Find and Replace All');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (232, 'en-US', 'NewNoteViewEditFindNext', 'Find Next');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (233, 'en-US', 'NewNoteViewEditFindPrevious', 'Find Previous');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (234, 'en-US', 'NewNoteViewEditReplaceWithinNote', 'Replace Within Note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (231, 'en-US', 'NewNoteViewEditFindWithinNote', 'Find Within Note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (227, 'en-US', 'NewNoteViewEditPaste', 'Paste');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (224, 'en-US', 'NewNoteViewEditRedo', 'Redo');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (229, 'en-US', 'NewNoteViewEditSelectAll', 'Select All');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (223, 'en-US', 'NewNoteViewEditUndo', 'Undo');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (241, 'en-US', 'NewNoteViewFont', 'Font');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (244, 'en-US', 'NewNoteViewCenter', 'Center');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (215, 'en-US', 'NewNoteViewFile', 'File');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (218, 'en-US', 'NewNoteViewFileAttach', 'Attach File');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (221, 'en-US', 'NewNoteViewFileClose', 'Close');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (220, 'en-US', 'NewNoteViewFileExport', 'Export');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (219, 'en-US', 'NewNoteViewFileImport', 'Import');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (216, 'en-US', 'NewNoteViewFileOpen', 'Open');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (217, 'en-US', 'NewNoteViewFileSave', 'Save');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (247, 'en-US', 'NewNoteViewIndent', 'Indent');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (248, 'en-US', 'NewNoteViewInsert', 'Insert');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (243, 'en-US', 'NewNoteViewLeft', 'Left');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (245, 'en-US', 'NewNoteViewRight', 'Right');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (242, 'en-US', 'NewNoteViewFontSize', 'Font Size');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (246, 'en-US', 'NewNoteViewUndent', 'Undent');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (237, 'en-US', 'NewNoteViewNote', 'Note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (238, 'en-US', 'NewNoteViewNoteCopy', 'Copy');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (240, 'en-US', 'NewNoteViewNoteDuplicate', 'Duplicate Note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (239, 'en-US', 'NewNoteViewNoteMove', 'Move');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (249, 'en-US', 'NewNoteViewShare', 'Share');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (250, 'en-US', 'NewNoteViewShareWithOthers', 'Share with others');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (235, 'en-US', 'NewNoteViewView', 'View');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (236, 'en-US', 'NewNoteViewViewStatusBar', 'View status bar');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (252, 'en-US', 'NotebookNotesMenuViewNotes', 'note(s)');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (251, 'en-US', 'NotebookNotesMenuViewTitle', 'Nameless notebook');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (255, 'en-US', 'NoteFeverViewAllNotes', 'All Notes');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (257, 'en-US', 'NoteFeverViewBin', 'Bin');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (253, 'en-US', 'NoteFeverViewChangeUser', 'Change user');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (254, 'en-US', 'NoteFeverViewNewNote', 'New Note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (259, 'en-US', 'NoteFeverViewSettings', 'Settings');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (256, 'en-US', 'NoteFeverViewSharedWithMe', 'Shared With Me');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (258, 'en-US', 'NoteFeverViewTags', 'Labels');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (264, 'en-US', 'RegisterViewConfirmPassword', 'Confirm Password');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (260, 'en-US', 'RegisterViewFirstName', 'First Name');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (261, 'en-US', 'RegisterViewLastName', 'Last Name');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (262, 'en-US', 'RegisterViewEmail', 'E-mail');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (263, 'en-US', 'RegisterViewPassword', 'Password');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (265, 'en-US', 'RegisterViewRegister', 'Register');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (268, 'en-US', 'TableRowColumnSpecifierViewCancel', 'Cancel');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (267, 'en-US', 'TableRowColumnSpecifierViewColumns', 'Insert the amount of columns:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (266, 'en-US', 'TableRowColumnSpecifierViewRows', 'Insert the amount of rows:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (269, 'en-US', 'TableRowColumnSpecifierViewSubmit', 'Submit');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (270, 'en-US', 'ValueRequestViewCancel', 'Cancel');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (271, 'en-US', 'ValueRequestViewSubmit', 'Submit');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (405, 'nl-NL', 'LoginViewLocal', 'Of gebruik het');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (514, 'nl-NL', 'TableRowColumnSpecifierViewSubmit', 'Akkoord');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (566, 'en-US', 'NoteFeverTreeViewModelAddNotebook', 'Add Notebook');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (567, 'en-US', 'NoteFeverTreeViewModelRemove', 'Remove');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (568, 'en-US', 'NoteFeverTreeViewModelAddNote', 'Add Note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (569, 'en-US', 'NoteFeverTreeViewModelMyNotebooks', 'My Notebooks');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (570, 'en-US', 'NoteFeverTreeViewModelTextBetween', 'Text should be between {0} and {1} characters long. Also it can''t contain the ''/'' character.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (571, 'en-US', 'NewNoteViewModelNamelessAuthor', 'Nameless author');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (572, 'en-US', 'NoteElementViewModelRestore', 'Restore');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (573, 'en-US', 'NoteElementViewModelDeletePermanently', 'Delete permanently');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (574, 'en-US', 'NoteElementViewModelRemove', 'Remove');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (575, 'en-US', 'NoteElementViewModelMove', 'Move');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (576, 'en-US', 'NoteElementViewModelShareNoteHeader', 'Share Note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (577, 'en-US', 'NoteFeverViewModelSharedNotes', 'Shared notes');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (578, 'en-US', 'NoteFeverViewModelAllNotes', 'All notes');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (579, 'en-US', 'NoteFeverViewModelBin', 'Bin');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (580, 'en-US', 'RegisterViewModelPleaseEmail', 'Please enter your email!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (581, 'en-US', 'RegisterViewModelPleasePassword', 'Please enter valid password!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (582, 'en-US', 'RegisterViewModelNotEqual', 'Password are not equal!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (583, 'en-US', 'RegisterViewModelUnknown', 'An unknown error occured!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (584, 'nl-NL', 'NoteElementViewModelUnsavedChanges', 'Weet u het zeker? Niet opgeslagen veranderingen gaan verloren!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (585, 'nl-NL', 'SettingViewModelSuccessfullySaved', 'Instellingen met succes opgeslagen!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (586, 'nl-NL', 'SettingViewModelWronglySaved', 'Er is iets fout gegaan tijdens get opslaan van de instellingen.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (587, 'nl-NL', 'SettingViewModelTitle', 'NoteFever | Instellingen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (588, 'nl-NL', 'TextBoxHelperOnlyGivenType', 'De gegeven input kan alleen maar van het volgende type zijn ');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (589, 'nl-NL', 'LoginViewModelSuccessfullyLoggedIn', 'U bent met succes ingelogd!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (590, 'nl-NL', 'LoginViewModelTitle', 'NoteFever | Inloggen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (591, 'nl-NL', 'LoginViewModelUnsuccessfullLoginAttempt', 'De gebruikersnaam of wachtwoord is niet correct, controleer de gegevens!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (592, 'nl-NL', 'NotebookPickerViewModelMoved', 'De notitie {0} is verplaatst naar het volgende notitieboek {1}/{2}');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (593, 'nl-NL', 'NotebookPickerViewModelTitle', 'NoteFever | Notitieboek kiezer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (594, 'nl-NL', 'NotebookPickerViewModelNotMoved', 'Het verplaatsen van de notitie naar het gespecificeerde notitieboek is niet gelukt!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (595, 'nl-NL', 'TableRowColumnSpecifierViewModelGreaterThanZero', 'Zorg dat de rijen en kolommen groter dan 0 zijn!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (596, 'nl-NL', 'MessageBoxTitleWarning', 'NoteFever | Waarschuwing');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (597, 'nl-NL', 'FieldsCantBeEmpty', 'Velden kunnen niet leeg zijn!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (598, 'nl-NL', 'MessageBoxTitleError', 'NoteFever | Fout');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (599, 'nl-NL', 'NewNoteViewModelLabelAlreadyExists', 'Dit label bestaat reeds!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (600, 'nl-NL', 'NoteElementViewModelPermanentlyDeleteNote', 'Weet je zeker dat je deze notitie permanent wilt verwijderen?');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (601, 'nl-NL', 'MessageBoxTitleFailed', 'NoteFever | Gefaald');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (602, 'nl-NL', 'NoteFeverViewModelCannotAddNoteToEmptyNotebook', 'U kunt geen nieuwe notitie toevoegen als er geen notitieboek is geselecteerd!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (603, 'nl-NL', 'NewNoteViewModelCantAddLabel', 'Je kan geen labels toevoegen aan notities niet niet opgeslagen zijn in de database!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (604, 'nl-NL', 'NoteElementViewModelLoggedInToUse', 'Je moet ingelogd zijn om deze functionaliteit te kunnen gebruiken.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (605, 'nl-NL', 'NoteElementViewModelShareNote', 'Voer a.u.b. een geldige gebruikersnaam in!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (606, 'nl-NL', 'NoteElementViewModelShareNoteTitle', 'NoteFever | Deel notitie');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (607, 'nl-NL', 'NewNoteViewModelAddLabel', 'Voer een label naam in');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (608, 'nl-NL', 'NewNoteViewModelAddLabelTitle', 'NoteFever | Label toevoegen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (609, 'nl-NL', 'RegisterViewModelRegisterSuccessful', 'Registratie succesvol!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (362, 'en-US', 'NewNoteViewInsertTable', 'Insert Table');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (363, 'en-US', 'NewNoteViewInsertHorizontalLine', 'Insert Horizontal Line');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (364, 'en-US', 'NewNoteViewInsertCode', 'Insert Code');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (365, 'en-US', 'NewNoteViewInsertOrderedList', 'Insert OrderedList');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (366, 'en-US', 'NewNoteViewInsertUnorderedList', 'Insert UnorderedList');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (367, 'en-US', 'NoteElementViewTitle', 'Nameless note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (368, 'en-US', 'NoteElementViewCreationDate', '05-07-1999');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (369, 'en-US', 'LoginViewWindowTitle', 'Login');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (370, 'en-US', 'NoteFeverWindowTitle', 'Note Fever');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (371, 'en-US', 'RegisterViewWindowTitle', 'Register');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (372, 'en-US', 'SettingsViewWindowTitle', 'Settings');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (373, 'en-US', 'SettingsViewTitle', 'Settings');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (374, 'en-US', 'SettingsViewEditor', 'Editor');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (375, 'en-US', 'SettingsViewStandards', 'Standards');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (376, 'en-US', 'SettingsViewLayout', 'Layout');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (377, 'en-US', 'SettingsViewLanguage', 'Language');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (378, 'en-US', 'NotebookPickerViewWindowTitle', 'Note Fever | specify notebook');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (379, 'en-US', 'NotebookPickerViewSpecifyANotebook', 'Specify a notebook to move the note to:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (380, 'en-US', 'NotebookPickerViewCancel', 'Cancel');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (381, 'en-US', 'NotebookPickerViewSubmit', 'Submit');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (382, 'en-US', 'TableRowColumnSpecifierViewWindowTitle', 'Note Fever | Specify table rows and columns');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (383, 'en-US', 'EditorViewFont', 'Default font:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (384, 'en-US', 'EditorViewFontSize', 'Default font size:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (385, 'en-US', 'EditorViewApplyChanges', 'Apply changes');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (386, 'en-US', 'EditorViewDefaultFont', 'Standard: Arial');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (387, 'en-US', 'EditorViewDefaultFontSize', 'Standard: 11');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (388, 'en-US', 'LanguageViewDisplayLanguage', 'Display language:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (389, 'en-US', 'LanguageViewDefaultDisplayLanguage', 'Standard: English (United States) / en-US');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (390, 'en-US', 'LanguageViewApplyChanges', 'Apply changes');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (391, 'en-US', 'LayoutViewButtonBackgroundColor', 'Button background color:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (392, 'en-US', 'LayoutViewDefaultButtonBackgroundColor', 'Standard: #404040');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (393, 'en-US', 'LayoutViewAccentColor', 'Accent color (e.g. Active button):');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (394, 'en-US', 'LayoutViewDefaultAccentColor', 'Standard: #0052cc');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (395, 'en-US', 'LayoutViewBackgroundColor', 'Background color settings:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (396, 'en-US', 'LayoutViewDefaultBackgroundColor', 'Standard: #ffbfcd');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (397, 'en-US', 'LayoutViewApplyChanges', 'Apply changes');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (398, 'en-US', 'StandardsViewNoteTitle', 'Default note title:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (399, 'en-US', 'StandardsViewDefaultNoteTitle', 'Standard: Nameless note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (400, 'en-US', 'StandardsViewNotebookTitle', 'Default notebook title:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (401, 'en-US', 'StandardsViewDefaultNotebookTitle', 'Standard: Nameless notebook');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (402, 'en-US', 'StandardsViewApplyChanges', 'Apply changes');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (403, 'en-US', 'StandardsViewLabelTitle', 'Default label title:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (404, 'en-US', 'StandardsViewDefaultLabelTitle', 'Standard: Nameless label');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (406, 'nl-NL', 'LoginViewLocalHyperlink', 'Lokaal');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (517, 'en-US', 'NoteElementViewModelUnsavedChanges', 'Are you sure? Unsaved changes will be lost.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (518, 'en-US', 'SettingViewModelSuccessfullySaved', 'Settings successfully saved!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (519, 'en-US', 'SettingViewModelWronglySaved', 'Something went wrong while trying to save settings.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (520, 'en-US', 'SettingViewModelTitle', 'NoteFever | Settings');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (521, 'en-US', 'TextBoxHelperOnlyGivenType', 'The given input can only be of type ');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (522, 'en-US', 'LoginViewModelSuccessfullyLoggedIn', 'You''ve been logged in with success!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (523, 'en-US', 'LoginViewModelTitle', 'NoteFever | Login');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (524, 'en-US', 'LoginViewModelUnsuccessfullLoginAttempt', 'Password or Username is not correct. Please check again.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (525, 'en-US', 'NotebookPickerViewModelMoved', 'The note {0} has been moved to the notebook {1}/{2}');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (526, 'en-US', 'NotebookPickerViewModelTitle', 'NoteFever | Notebook Picker');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (527, 'en-US', 'NotebookPickerViewModelNotMoved', 'Failed to move the note to the specified notebook.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (528, 'en-US', 'TableRowColumnSpecifierViewModelGreaterThanZero', 'Please make sure that both the rows and columns are greater than 0');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (529, 'en-US', 'MessageBoxTitleWarning', 'NoteFever | Warning');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (530, 'en-US', 'FieldsCantBeEmpty', 'Fields can''t be empty!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (531, 'en-US', 'MessageBoxTitleError', 'NoteFever | Error');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (532, 'en-US', 'NewNoteViewModelLabelAlreadyExists', 'This label already exists!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (533, 'en-US', 'NoteElementViewModelPermanentlyDeleteNote', 'Are you sure that you want to permanently delete this note?');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (534, 'en-US', 'MessageBoxTitleFailed', 'NoteFever | Failed');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (535, 'en-US', 'NoteFeverViewModelCannotAddNoteToEmptyNotebook', 'Cannot add new notes whilst not in a notebook');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (536, 'en-US', 'NewNoteViewModelCantAddLabel', 'You can''t add labels to notes when they''re not saved in the database.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (537, 'en-US', 'NoteElementViewModelLoggedInToUse', 'You have to be logged in to use this functionality!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (538, 'en-US', 'NoteElementViewModelShareNote', 'Please enter a valid username');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (539, 'en-US', 'NoteElementViewModelShareNoteTitle', 'NoteFever | Share Note');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (540, 'en-US', 'NewNoteViewModelAddLabel', 'Enter a label name');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (541, 'en-US', 'NewNoteViewModelAddLabelTitle', 'NoteFever | Add Label');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (542, 'en-US', 'RegisterViewModelRegisterSuccessful', 'Registration successful!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (543, 'en-US', 'MessageBoxTitleSuccessful', 'NoteFever | Success');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (544, 'en-US', 'RegisterViewModelRegistrationFailed', 'Registration failed! Please try again.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (545, 'en-US', 'RegisterViewModelFieldsWithErrors', 'Please fill in the fields with errors');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (546, 'en-US', 'NoteFeverViewModelNoNotes', 'There are no notes to view.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (547, 'en-US', 'NoteFeverViewModelNoSharedNotes', 'There are no shared notes to view.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (548, 'en-US', 'MessageBoxTitleNotice', 'NoteFever | Notice');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (549, 'en-US', 'NoteElementViewModelSharedNote', 'Successfully shared the note with {0}!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (550, 'en-US', 'NoteElementViewModelShareNoteUsernameDoesNotExist', 'Username does not exist or make sure you''re logged in.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (551, 'en-US', 'NewNoteViewModelSavedNote', 'Note was saved successfully!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (552, 'en-US', 'NewNoteViewModelCouldntSaveNote', 'We were unable to save your note.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (553, 'en-US', 'NotefeverViewModelNoDeletedNotes', 'There are no deleted notes.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (554, 'en-US', 'LoginViewModelGoogleLogin', 'You''ve been logged in with a Google account.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (555, 'en-US', 'RichTextEditorCommandsProvideHexadecimal', 'Please provide a valid hexadecimal color.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (556, 'en-US', 'NoteFeverTreeViewModelNoMoreThan', 'You can''t have more than 10 nested folders!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (557, 'en-US', 'NoteFeverTreeViewModelNewFolderTitle', 'NoteFever | Create new folder');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (558, 'en-US', 'NoteFeverTreeViewModelNewFolder', 'What do you want your new folder to be called:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (559, 'en-US', 'NoteFeverTreeViewModelErrorWhileNewFolder', 'Something happened while adding the folder');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (560, 'en-US', 'NoteFeverTreeViewModelNewNotebookTitle', 'NoteFever | Create new notebook');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (561, 'en-US', 'NoteFeverTreeViewModelNewNotebook', 'What do you want your new notebook to be called:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (562, 'en-US', 'NoteFeverTreeViewModelErrorWhileNewNotebook', 'Something happened while adding the notebook');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (563, 'en-US', 'RichTextEditorCommandsColorTitle', 'Pick a color');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (564, 'en-US', 'RichTextEditorCommandsInsertHEX', 'Insert a HEX color to change the color to (without the ''#'')');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (565, 'en-US', 'NoteFeverTreeViewModelAddFolder', 'Add Folder');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (407, 'nl-NL', 'LoginViewLogin', 'Inloggen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (408, 'nl-NL', 'LoginViewPassword', 'Wachtwoord');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (409, 'nl-NL', 'LoginViewRegister', 'Registreer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (410, 'nl-NL', 'LoginViewUsername', 'Gebruikersnaam');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (411, 'nl-NL', 'NewNoteViewEditDelete', 'Verwijder');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (412, 'nl-NL', 'NewNoteViewEdit', 'Bewerk');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (413, 'nl-NL', 'NewNoteViewEditCopy', 'Kopieer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (414, 'nl-NL', 'NewNoteViewEditCut', 'Knip');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (415, 'nl-NL', 'NewNoteViewEditFindAndReplaceAll', 'Vind en verplaats alle');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (416, 'nl-NL', 'NewNoteViewEditFindNext', 'Vind volgende');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (417, 'nl-NL', 'NewNoteViewEditFindPrevious', 'Vind vorige');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (418, 'nl-NL', 'NewNoteViewEditReplaceWithinNote', 'Verplaats binnen notitie');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (419, 'nl-NL', 'NewNoteViewEditFindWithinNote', 'Vind binnen notitie');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (420, 'nl-NL', 'NewNoteViewEditPaste', 'Plak');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (421, 'nl-NL', 'NewNoteViewEditRedo', 'Opnieuw doen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (422, 'nl-NL', 'NewNoteViewEditSelectAll', 'Selecteer alles');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (423, 'nl-NL', 'NewNoteViewEditUndo', 'Ongedaan maken');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (424, 'nl-NL', 'NewNoteViewFont', 'Lettertype');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (425, 'nl-NL', 'NewNoteViewCenter', 'Midden');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (426, 'nl-NL', 'NewNoteViewFile', 'Bestand');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (427, 'nl-NL', 'NewNoteViewFileAttach', 'Voeg bijlage toe');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (428, 'nl-NL', 'NewNoteViewFileClose', 'Sluit');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (429, 'nl-NL', 'NewNoteViewFileExport', 'Exporteer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (430, 'nl-NL', 'NewNoteViewFileImport', 'Importeer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (431, 'nl-NL', 'NewNoteViewFileOpen', 'Open');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (432, 'nl-NL', 'NewNoteViewFileSave', 'Opslaan');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (433, 'nl-NL', 'NewNoteViewIndent', 'Inspringen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (434, 'nl-NL', 'NewNoteViewInsert', 'Invoegen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (435, 'nl-NL', 'NewNoteViewLeft', 'Links');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (436, 'nl-NL', 'NewNoteViewRight', 'Rechts');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (437, 'nl-NL', 'NewNoteViewFontSize', 'Lettertype grootte');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (438, 'nl-NL', 'NewNoteViewUndent', 'TerugSpringen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (439, 'nl-NL', 'NewNoteViewNote', 'Notitie');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (440, 'nl-NL', 'NewNoteViewNoteCopy', 'Kopieer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (441, 'nl-NL', 'NewNoteViewNoteDuplicate', 'Dupliceer notitie');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (442, 'nl-NL', 'NewNoteViewNoteMove', 'Verplaats');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (443, 'nl-NL', 'NewNoteViewShare', 'Deel');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (444, 'nl-NL', 'NewNoteViewShareWithOthers', 'Deel met anderen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (445, 'nl-NL', 'NewNoteViewView', 'Bekijk');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (446, 'nl-NL', 'NewNoteViewViewStatusBar', 'Bekijk statusbalk');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (447, 'nl-NL', 'NotebookNotesMenuViewNotes', 'notitie(s)');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (448, 'nl-NL', 'NotebookNotesMenuViewTitle', 'Naamloos notitieboek');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (449, 'nl-NL', 'NoteFeverViewAllNotes', 'Alle notities');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (450, 'nl-NL', 'NoteFeverViewBin', 'Prullenbak');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (451, 'nl-NL', 'NoteFeverViewChangeUser', 'Verander van gebruiker');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (452, 'nl-NL', 'NoteFeverViewNewNote', 'Nieuwe notitie');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (453, 'nl-NL', 'NoteFeverViewSettings', 'Instellingen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (454, 'nl-NL', 'NoteFeverViewSharedWithMe', 'Gedeeld met mij');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (455, 'nl-NL', 'NoteFeverViewTags', 'Labels');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (456, 'nl-NL', 'RegisterViewConfirmPassword', 'Bevestig wachtwoord');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (457, 'nl-NL', 'RegisterViewFirstName', 'Voornaam');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (458, 'nl-NL', 'RegisterViewLastName', 'Achternaam');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (459, 'nl-NL', 'RegisterViewEmail', 'E-mail');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (460, 'nl-NL', 'RegisterViewPassword', 'Wachtwoord');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (461, 'nl-NL', 'RegisterViewRegister', 'Registreer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (462, 'nl-NL', 'TableRowColumnSpecifierViewCancel', 'Annuleer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (463, 'nl-NL', 'TableRowColumnSpecifierViewColumns', 'Voer het aantal kolommen in:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (464, 'nl-NL', 'TableRowColumnSpecifierViewRows', 'Voer het aantal rijen in:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (466, 'nl-NL', 'ValueRequestViewCancel', 'Annuleer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (467, 'nl-NL', 'ValueRequestViewSubmit', 'Akkoord');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (468, 'nl-NL', 'NewNoteViewInsertTable', 'Tabel invoegen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (469, 'nl-NL', 'NewNoteViewInsertHorizontalLine', 'Horizontale lijn invoegen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (470, 'nl-NL', 'NewNoteViewInsertCode', 'Code invoegen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (471, 'nl-NL', 'NewNoteViewInsertOrderedList', 'Geordende lijst invoegen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (472, 'nl-NL', 'NewNoteViewInsertUnorderedList', 'Ongeordende lijst invoegen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (473, 'nl-NL', 'NoteElementViewTitle', 'Naamloze notitie invoegen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (474, 'nl-NL', 'NoteElementViewCreationDate', '05-07-1999');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (475, 'nl-NL', 'LoginViewWindowTitle', 'Inloggen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (476, 'nl-NL', 'NoteFeverWindowTitle', 'Note Fever');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (477, 'nl-NL', 'RegisterViewWindowTitle', 'Registreren');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (478, 'nl-NL', 'SettingsViewWindowTitle', 'Instellingen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (479, 'nl-NL', 'SettingsViewTitle', 'Settings');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (480, 'nl-NL', 'SettingsViewEditor', 'Editor');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (481, 'nl-NL', 'SettingsViewStandards', 'Standaarden');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (482, 'nl-NL', 'SettingsViewLayout', 'Uiterlijk');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (483, 'nl-NL', 'SettingsViewLanguage', 'Taal');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (484, 'nl-NL', 'NotebookPickerViewWindowTitle', 'Note Fever | specificeer een notitieboek');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (485, 'nl-NL', 'NotebookPickerViewSpecifyANotebook', 'Specificeer een notitieboek om de geselecteerde notitie naar te berplaatsen:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (486, 'nl-NL', 'NotebookPickerViewCancel', 'Annuleer');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (487, 'nl-NL', 'NotebookPickerViewSubmit', 'Akkoord');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (488, 'nl-NL', 'TableRowColumnSpecifierViewWindowTitle', 'Note Fever | Specificeer tabel rijen en kolommen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (489, 'nl-NL', 'EditorViewFont', 'Standaard lettertype:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (490, 'nl-NL', 'EditorViewFontSize', 'Standaard lettertype grootte:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (491, 'nl-NL', 'EditorViewApplyChanges', 'Wijzigingen opslaan');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (492, 'nl-NL', 'EditorViewDefaultFont', 'Standaard: Arial');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (493, 'nl-NL', 'EditorViewDefaultFontSize', 'Standaard: 11');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (494, 'nl-NL', 'LanguageViewDisplayLanguage', 'Schermtaal:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (495, 'nl-NL', 'LanguageViewDefaultDisplayLanguage', 'Standaard: Engels (United States) / en-US');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (496, 'nl-NL', 'LanguageViewApplyChanges', 'Wijzigingen aanbrengen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (497, 'nl-NL', 'LayoutViewButtonBackgroundColor', 'Knop achtergrond kleur:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (498, 'nl-NL', 'LayoutViewDefaultButtonBackgroundColor', 'Standaard: #404040');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (499, 'nl-NL', 'LayoutViewAccentColor', 'Accent kleur (b.v. Actieve knop):');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (500, 'nl-NL', 'LayoutViewDefaultAccentColor', 'Standaard: #0052cc');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (501, 'nl-NL', 'LayoutViewBackgroundColor', 'Instellingen achtergrond kleur:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (502, 'nl-NL', 'LayoutViewDefaultBackgroundColor', 'Standaard: #ffbfcd');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (503, 'nl-NL', 'LayoutViewApplyChanges', 'Wijzigingen aanbrengen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (504, 'nl-NL', 'StandardsViewNoteTitle', 'Standaard notitie titel:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (505, 'nl-NL', 'StandardsViewDefaultNoteTitle', 'Standaard: Naamloze titel');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (506, 'nl-NL', 'StandardsViewNotebookTitle', 'Standaard notitieboek titel:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (507, 'nl-NL', 'StandardsViewDefaultNotebookTitle', 'Standaard: Naamloos notitieboek');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (508, 'nl-NL', 'StandardsViewApplyChanges', 'Wijzigingen aanbrengen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (509, 'nl-NL', 'StandardsViewLabelTitle', 'Standaard label titel:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (510, 'nl-NL', 'StandardsViewDefaultLabelTitle', 'Standaard: Naamloos label');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (610, 'nl-NL', 'MessageBoxTitleSuccessful', 'NoteFever | Succes');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (611, 'nl-NL', 'RegisterViewModelRegistrationFailed', 'Er is iets mis gegaan tijdens het registreren. Probeer het opnieuw.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (612, 'nl-NL', 'RegisterViewModelFieldsWithErrors', 'Voer de velden die fouten bevatten opnieuw in.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (613, 'nl-NL', 'NoteFeverViewModelNoNotes', 'Er zijn geen notities om te laten zien.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (614, 'nl-NL', 'NoteFeverViewModelNoSharedNotes', 'Er zijn geen gedeelde notities om te laten zien.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (615, 'nl-NL', 'MessageBoxTitleNotice', 'NoteFever | Opmerking');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (616, 'nl-NL', 'NoteElementViewModelSharedNote', 'De notitie is met succes gedeeld met {0}!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (617, 'nl-NL', 'NoteElementViewModelShareNoteUsernameDoesNotExist', 'Die gebruikersnaam bestaat niet, je moet ook ingelogd zijn om deze functionaliteit te gebruiken!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (618, 'nl-NL', 'NewNoteViewModelSavedNote', 'De notitie is met succes opgeslagen.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (619, 'nl-NL', 'NewNoteViewModelCouldntSaveNote', 'We waren niet in staat de notitie op te slaan.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (620, 'nl-NL', 'NotefeverViewModelNoDeletedNotes', 'Er zijn geen verwijderde notities.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (621, 'nl-NL', 'LoginViewModelGoogleLogin', 'Je bent ingelogd met een Google account.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (622, 'nl-NL', 'RichTextEditorCommandsProvideHexadecimal', 'Voer a.u.b. een geldige hexadecimale waarde in.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (623, 'nl-NL', 'NoteFeverTreeViewModelNoMoreThan', 'Je mag niet meer dan 10 geneste mappen hebben.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (624, 'nl-NL', 'NoteFeverTreeViewModelNewFolderTitle', 'NoteFever | Maak een nieuwe map');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (625, 'nl-NL', 'NoteFeverTreeViewModelNewFolder', 'Hoe moet de nieuwe map heten:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (626, 'nl-NL', 'NoteFeverTreeViewModelErrorWhileNewFolder', 'Er is een fout opgetreden tijdens het toevoegen van een nieuwe map!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (627, 'nl-NL', 'NoteFeverTreeViewModelNewNotebookTitle', 'NoteFever | Maak een nieuw notitieboek');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (628, 'nl-NL', 'NoteFeverTreeViewModelNewNotebook', 'Hoe moet het nieuwe notitieboek heten:');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (629, 'nl-NL', 'NoteFeverTreeViewModelErrorWhileNewNotebook', 'Er is een fout opgetreden tijdens het toevoegen van een nieuw notitieboek!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (630, 'nl-NL', 'RichTextEditorCommandsColorTitle', 'Kies een kleur.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (631, 'nl-NL', 'RichTextEditorCommandsInsertHEX', 'Voer een hexadecimale waarde in wat de nieuwe kleur moet worden (zonder de ''#'')');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (632, 'nl-NL', 'NoteFeverTreeViewModelAddFolder', 'Nieuwe Map');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (633, 'nl-NL', 'NoteFeverTreeViewModelAddNotebook', 'Nieuw Notitieboek');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (634, 'nl-NL', 'NoteFeverTreeViewModelRemove', 'Verwijder');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (635, 'nl-NL', 'NoteFeverTreeViewModelAddNote', 'Nieuwe Notitie');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (636, 'nl-NL', 'NoteFeverTreeViewModelMyNotebooks', 'Mijn Notitieboeken');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (637, 'nl-NL', 'NoteFeverTreeViewModelTextBetween', 'De tekst moet tussen de {0} en {1} karakters lang zijn. Het mag ook GEEN ''/'' karakter bevatten.');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (638, 'nl-NL', 'NewNoteViewModelNamelessAuthor', 'Naamloze auteur');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (639, 'nl-NL', 'NoteElementViewModelRestore', 'Herstellen');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (640, 'nl-NL', 'NoteElementViewModelDeletePermanently', 'Verwijder permanent');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (641, 'nl-NL', 'NoteElementViewModelRemove', 'Verwijder');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (642, 'nl-NL', 'NoteElementViewModelMove', 'Verplaats');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (643, 'nl-NL', 'NoteElementViewModelShareNoteHeader', 'Deel notitie');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (644, 'nl-NL', 'NoteFeverViewModelSharedNotes', 'Gedeelde notities');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (645, 'nl-NL', 'NoteFeverViewModelAllNotes', 'Alle notities');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (646, 'nl-NL', 'NoteFeverViewModelBin', 'Prullenbak');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (647, 'nl-NL', 'RegisterViewModelPleaseEmail', 'Voer je email a.u.b. in!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (648, 'nl-NL', 'RegisterViewModelPleasePassword', 'Voer een geldig wachtwoord in!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (649, 'nl-NL', 'RegisterViewModelNotEqual', 'Wachtwoorden zijn niet hetzelfde!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (650, 'nl-NL', 'RegisterViewModelUnknown', 'Er is een onbekende fout opgetreden!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (651, 'en-US', 'RegisterViewModelAlreadyExists', 'A user with that username (email) already exists!');
INSERT INTO NoteFever_EvernoteClone.dbo.Language (Id, Language, Keyword, Translation) VALUES (652, 'nl-NL', 'RegisterViewModelAlreadyExists', 'Een gebruiker met die gebruikersnaam (email) bestaat al!');

SET IDENTITY_INSERT NoteFever_EvernoteClone.dbo.Language OFF;