@startuml
class PasswordHelper <<static>> {
    + {static} SetAttach(dp:DependencyObject, value:bool) : void
    + {static} GetAttach(dp:DependencyObject) : bool
    + {static} GetPassword(dp:DependencyObject) : string
    + {static} SetPassword(dp:DependencyObject, value:string) : void
    - {static} GetIsUpdating(dp:DependencyObject) : bool
    - {static} SetIsUpdating(dp:DependencyObject, value:bool) : void
    - {static} OnPasswordPropertyChanged(sender:DependencyObject, e:DependencyPropertyChangedEventArgs) : void
    - {static} Attach(sender:DependencyObject, e:DependencyPropertyChangedEventArgs) : void
    - {static} PasswordChanged(sender:object, e:RoutedEventArgs) : void
}
PasswordHelper o-> "PasswordProperty" DependencyProperty
PasswordHelper o-> "AttachProperty" DependencyProperty
PasswordHelper o-> "IsUpdatingProperty" DependencyProperty
@enduml
