//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvernoteCloneGUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvernoteCloneGUI.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or use it.
        /// </summary>
        public static string LoginViewLoca {
            get {
                return ResourceManager.GetString("LoginViewLoca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locally.
        /// </summary>
        public static string LoginViewLocaBut {
            get {
                return ResourceManager.GetString("LoginViewLocaBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginViewLogin {
            get {
                return ResourceManager.GetString("LoginViewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginViewPass {
            get {
                return ResourceManager.GetString("LoginViewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LoginViewRegi {
            get {
                return ResourceManager.GetString("LoginViewRegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginViewUsern {
            get {
                return ResourceManager.GetString("LoginViewUsern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string NewNoteViewEdit {
            get {
                return ResourceManager.GetString("NewNoteViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string NewNoteViewEditCopy {
            get {
                return ResourceManager.GetString("NewNoteViewEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string NewNoteViewEditCut {
            get {
                return ResourceManager.GetString("NewNoteViewEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string NewNoteViewEditDeletet {
            get {
                return ResourceManager.GetString("NewNoteViewEditDeletet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace All.
        /// </summary>
        public static string NewNoteViewEditFind {
            get {
                return ResourceManager.GetString("NewNoteViewEditFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string NewNoteViewEditFindNext {
            get {
                return ResourceManager.GetString("NewNoteViewEditFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string NewNoteViewEditFindPrev {
            get {
                return ResourceManager.GetString("NewNoteViewEditFindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Within Note.
        /// </summary>
        public static string NewNoteViewEditFindReo {
            get {
                return ResourceManager.GetString("NewNoteViewEditFindReo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Within Note.
        /// </summary>
        public static string NewNoteViewEditFindWith {
            get {
                return ResourceManager.GetString("NewNoteViewEditFindWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string NewNoteViewEditPaste {
            get {
                return ResourceManager.GetString("NewNoteViewEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string NewNoteViewEditRedo {
            get {
                return ResourceManager.GetString("NewNoteViewEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string NewNoteViewEditSelect {
            get {
                return ResourceManager.GetString("NewNoteViewEditSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string NewNoteViewEditUndo {
            get {
                return ResourceManager.GetString("NewNoteViewEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string NewNoteViewF {
            get {
                return ResourceManager.GetString("NewNoteViewF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string NewNoteViewFcenter {
            get {
                return ResourceManager.GetString("NewNoteViewFcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string NewNoteViewFile {
            get {
                return ResourceManager.GetString("NewNoteViewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach File.
        /// </summary>
        public static string NewNoteViewFileAttach {
            get {
                return ResourceManager.GetString("NewNoteViewFileAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string NewNoteViewFileClose {
            get {
                return ResourceManager.GetString("NewNoteViewFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string NewNoteViewFileExport {
            get {
                return ResourceManager.GetString("NewNoteViewFileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string NewNoteViewFileImport {
            get {
                return ResourceManager.GetString("NewNoteViewFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string NewNoteViewFileOpen {
            get {
                return ResourceManager.GetString("NewNoteViewFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NewNoteViewFileSave {
            get {
                return ResourceManager.GetString("NewNoteViewFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        public static string NewNoteViewFindent {
            get {
                return ResourceManager.GetString("NewNoteViewFindent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string NewNoteViewFinsert {
            get {
                return ResourceManager.GetString("NewNoteViewFinsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codeblocks.
        /// </summary>
        public static string NewNoteViewFinsertCode {
            get {
                return ResourceManager.GetString("NewNoteViewFinsertCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal line.
        /// </summary>
        public static string NewNoteViewFinsertHorLine {
            get {
                return ResourceManager.GetString("NewNoteViewFinsertHorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered list.
        /// </summary>
        public static string NewNoteViewFinsertOr {
            get {
                return ResourceManager.GetString("NewNoteViewFinsertOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string NewNoteViewFinsertTable {
            get {
                return ResourceManager.GetString("NewNoteViewFinsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unordered list.
        /// </summary>
        public static string NewNoteViewFinsertUnor {
            get {
                return ResourceManager.GetString("NewNoteViewFinsertUnor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string NewNoteViewFleft {
            get {
                return ResourceManager.GetString("NewNoteViewFleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string NewNoteViewFright {
            get {
                return ResourceManager.GetString("NewNoteViewFright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string NewNoteViewFsize {
            get {
                return ResourceManager.GetString("NewNoteViewFsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undent.
        /// </summary>
        public static string NewNoteViewFundent {
            get {
                return ResourceManager.GetString("NewNoteViewFundent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NewNoteViewNote {
            get {
                return ResourceManager.GetString("NewNoteViewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string NewNoteViewNoteCopy {
            get {
                return ResourceManager.GetString("NewNoteViewNoteCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Note.
        /// </summary>
        public static string NewNoteViewNoteDup {
            get {
                return ResourceManager.GetString("NewNoteViewNoteDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string NewNoteViewNoteMove {
            get {
                return ResourceManager.GetString("NewNoteViewNoteMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string NewNoteViewShare {
            get {
                return ResourceManager.GetString("NewNoteViewShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share with others.
        /// </summary>
        public static string NewNoteViewShareOp {
            get {
                return ResourceManager.GetString("NewNoteViewShareOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string NewNoteViewView {
            get {
                return ResourceManager.GetString("NewNoteViewView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View status bar.
        /// </summary>
        public static string NewNoteViewViewBar {
            get {
                return ResourceManager.GetString("NewNoteViewViewBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string NotebookNotesMenuViewNumber {
            get {
                return ResourceManager.GetString("NotebookNotesMenuViewNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameless notebook.
        /// </summary>
        public static string NotebookNotesMenuViewTitle {
            get {
                return ResourceManager.GetString("NotebookNotesMenuViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Notes.
        /// </summary>
        public static string NoteFeverViewAllN {
            get {
                return ResourceManager.GetString("NoteFeverViewAllN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        public static string NoteFeverViewBin {
            get {
                return ResourceManager.GetString("NoteFeverViewBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change user.
        /// </summary>
        public static string NoteFeverViewChange {
            get {
                return ResourceManager.GetString("NoteFeverViewChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Note.
        /// </summary>
        public static string NoteFeverViewNewN {
            get {
                return ResourceManager.GetString("NoteFeverViewNewN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string NoteFeverViewSearch {
            get {
                return ResourceManager.GetString("NoteFeverViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared With Me.
        /// </summary>
        public static string NoteFeverViewShared {
            get {
                return ResourceManager.GetString("NoteFeverViewShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string NoteFeverViewTags {
            get {
                return ResourceManager.GetString("NoteFeverViewTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string RegisterViewCpass {
            get {
                return ResourceManager.GetString("RegisterViewCpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string RegisterViewFname {
            get {
                return ResourceManager.GetString("RegisterViewFname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string RegisterViewLname {
            get {
                return ResourceManager.GetString("RegisterViewLname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string RegisterViewMail {
            get {
                return ResourceManager.GetString("RegisterViewMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterViewMess {
            get {
                return ResourceManager.GetString("RegisterViewMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterViewPass {
            get {
                return ResourceManager.GetString("RegisterViewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterViewRegi {
            get {
                return ResourceManager.GetString("RegisterViewRegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TableRowColumnSpecifierViewCancel {
            get {
                return ResourceManager.GetString("TableRowColumnSpecifierViewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert tje amount of columns:.
        /// </summary>
        public static string TableRowColumnSpecifierViewCulomns {
            get {
                return ResourceManager.GetString("TableRowColumnSpecifierViewCulomns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the amount of rows:.
        /// </summary>
        public static string TableRowColumnSpecifierViewRows {
            get {
                return ResourceManager.GetString("TableRowColumnSpecifierViewRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string TableRowColumnSpecifierViewSubmit {
            get {
                return ResourceManager.GetString("TableRowColumnSpecifierViewSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ValueRequestViewCancel {
            get {
                return ResourceManager.GetString("ValueRequestViewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ValueRequestViewSubmit {
            get {
                return ResourceManager.GetString("ValueRequestViewSubmit", resourceCulture);
            }
        }
    }
}
